### ISSUE TITLE
Can  DuckDB query DataFrames.jl data directly ?

### ISSUE THREAD

**Issue by zsz00** [kimmolinna/DuckDB.jl#5]
As far as I known DuckDB can query Arrow datasets directly and stream query results back to Arrow, 

Can  DuckDB query DataFrames.jl data directly and stream query results back to DataFrames ?

**Comment by kimmolinna** [comment]
No, It can't. The integration with Arrow is built-in in DuckDB.

**Comment by jeremiahpslewis** [comment]
I suppose one *might* be able to do some sort of DataFrames -> Arrow.jl -> DuckDB -> DataFrames loop, but if you already have the dataset in memory in a DataFrame, I might first look at manipulating it in place using https://github.com/jkrumbiegel/DataFrameMacros.jl or a similar package...

**Comment by zsz00** [comment]
OK, I see.  tks
