### ISSUE TITLE
Can't query parquet files?

### ISSUE THREAD

**Issue by tdunning** [kimmolinna/DuckDB.jl#6]
I have tried the following from the duckDB docs:
```
D select count(1) from parquet_scan('test.parquet');
┌──────────┐
│ count(1) │
├──────────┤
│ 15369    │
└──────────┘
D 
```

That's cool. And fast :O)

But from Julia, I try this
```
julia> using DuckDB
julia> res = DuckDB.execute(con, """SELECT * FROM parquet_scan('test.parquet');""")
Catalog Error: Table Function with name parquet_scan does not exist!
Did you mean "arrow_scan"?
LINE 1: SELECT * FROM parquet_scan('test.parquet');
                      ^Base.RefValue{DuckDB.duckdb_result}(DuckDB.duckdb_result(Ptr{UInt64} @0x0000000000000000, Ptr{UInt64} @0x0000000000000000, Ptr{UInt64} @0x0000000000000000, Ptr{DuckDB.duckdb_column} @0x0000000000000000, Ptr{UInt8} @0x0000000004415ec0, Ptr{Nothing} @0x0000000000000000))
```
That's sad.

On the other hand, `csv` seems to work:
```
julia> DuckDB.toDataFrame(DuckDB.execute(con, """select * from 't1.csv' """))
4×2 DataFrame
 Row │ x      t     
     │ Int32  Int32 
─────┼──────────────
   1 │     1      1
   2 │     2      1
   3 │     3      1
   4 │     2      1
```

Any ideas?

**Comment by tdunning** [comment]
This seems to be due to this package depending on commit d9bced of duckdb which is from August 2020.

**Comment by tdunning** [comment]
OK. This is confusing. I just added DuckDB directly from this repo. 
```
(@v1.6) pkg> add https://github.com/kimmolinna/DuckDB.jl
    Updating git-repo `https://github.com/kimmolinna/DuckDB.jl`
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [d2f5444f] + DuckDB v0.2.6 `https://github.com/kimmolinna/DuckDB.jl#main`
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [a10d1c49] + DBInterface v2.5.0
  [d2f5444f] + DuckDB v0.2.6 `https://github.com/kimmolinna/DuckDB.jl#main`
  [2cbbab25] + DuckDB_jll v0.3.0+0
```
This shows a dependency on `DuckDB_jll v0.3.0+0` which I thought had parquet support built in.

But I still get the `parquet_scan` not defined sort of problem.

**Comment by kimmolinna** [comment]
I should update the package. I will do it later today. The parquet support was added automatically to the version 0.3.1.

**Comment by tdunning** [comment]
Ah... very cool!

Btw.. your linked in profile is surprising. Are you actually an active pilot AND doing this?

**Comment by kimmolinna** [comment]
Yes, I am. Unfortunately I have been laid off from a cockpit work for a while now due to COVID but I should start flying in April again. And hopefully I can work then partly in the cockpit and partly in the office as I used to do earlier.

**Comment by jeremiahpslewis** [comment]
@kimmolinna DuckDB_jll 0.3.1 is now available on Yggdrasil and should install automatically with `Pkg.update()` as DuckDB.jl doesn't version pin :)

**Comment by tdunning** [comment]
Well that is pretty impressive to stay current *and* play with software. Congrats on a hoped for return to the cockpit.

I am testing the new version now. If successful, I will update the comments I made on slack.

**Comment by tdunning** [comment]
Hmm... I don't understand what is happening. Still don't see parquet stuff.

The history on Yggdrasil is also a bit odd. I saw a commit from November 10 (ddb4a3344002b144a7f9442ca4960a28502ca870 by kimmolinna) but now that seems replaced by one from about 12 hours ago (c6f29785aa214584216d51af0da78dbe99f53790 by jeremiahpslewis) that does roughly the same things plus some formatting. The package on my machine seemed right but I removed it, re-added it and restarted julia.

I see the dependency on DuckDB_jll v0.3.1+1, but I see no change in behavior. Adding DuckDB from the registry versus directly from kimmolinna's repo seems identical (as it should be).

This all seems sooo close that I can taste it. Am I doing something sideways?

```
(@v1.6) pkg> add DuckDB
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [d2f5444f] + DuckDB v0.2.6
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [a10d1c49] + DBInterface v2.5.0
  [d2f5444f] + DuckDB v0.2.6
  [2cbbab25] + DuckDB_jll v0.3.1+1
Precompiling project...
  1 dependency successfully precompiled in 5 seconds (305 already precompiled)

julia> con = DuckDB.connect(":memory:")
Base.RefValue{Ptr{Nothing}}(Ptr{Nothing} @0x0000000002528fb0)

julia> res = DuckDB.execute(con, """SELECT * FROM 'test.parquet' limit 10;""")
Catalog Error: Table with name test.parquet does not exist!
LINE 1: SELECT * FROM 'test.parquet' limit 10;
                      ^Base.RefValue{DuckDB.duckdb_result}(DuckDB.duckdb_result(Ptr{UInt64} @0x0000000000000000, Ptr{UInt64} @0x0000000000000000, Ptr{UInt64} @0x0000000000000000, Ptr{DuckDB.duckdb_column} @0x0000000000000000, Ptr{UInt8} @0x00000000028e7aa0, Ptr{Nothing} @0x0000000000000000))

julia> 
tdunning@nodea:~$ ./duckdb
v0.3.1 88aa81c6b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select * from 'test.parquet' limit 10;
┌────────────────────┬───────────────┬───────────────┐
│         h3         │       t       │ precipitation │
├────────────────────┼───────────────┼───────────────┤
│ 644772391210059915 │ 1640304000000 │ 0.0           │
│ 644772391212081504 │ 1640304000000 │ 0.0           │
│ 644772391217150984 │ 1640304000000 │ 0.0           │
│ 644772406232002947 │ 1640304000000 │ 0.0           │
│ 644772406243808618 │ 1640304000000 │ 0.0           │
│ 644772406246597538 │ 1640304000000 │ 0.0           │
│ 644772406247068262 │ 1640304000000 │ 0.0           │
│ 644772406248243803 │ 1640304000000 │ 0.0           │
│ 644772407319075977 │ 1640304000000 │ 0.0           │
│ 644772407321703180 │ 1640304000000 │ 0.0           │
└────────────────────┴───────────────┴───────────────┘
D 
```

**Comment by jeremiahpslewis** [comment]
Could it be a path issue? Maybe try using the absolute path instead of a relative one?

(As for the Yggdrasil, you're right that there are two 0.3.1 builds, but that shouldn't play a role)

**Comment by tdunning** [comment]
The question of path was the motive for my trying with an explicit call to `parquet_scan` and for trying the csv format as well.

In any case, the absolute path fails identically:
```
julia> res = DuckDB.execute(con, """SELECT * FROM parquet_scan('/home/tdunning/test.parquet');""")
Catalog Error: Table Function with name parquet_scan does not exist!
Did you mean "arrow_scan"?
LINE 1: SELECT * FROM parquet_scan('/home/tdunning/test.parqu...
                      ^Base.RefValue{DuckDB.duckdb_result}(DuckDB.duckdb_result(Ptr{UInt64} @0x0000000000000000, Ptr{UInt64} @0x0000000000000000, Ptr{UInt64} @0x0000000000000000, Ptr{DuckDB.duckdb_column} @0x0000000000000000, Ptr{UInt8} @0x000000000159f8d0, Ptr{Nothing} @0x0000000000000000))
```

**Comment by tdunning** [comment]
Well, here is an odd data point (so odd that I think it is not entirely real). This really does indicate some breakage somewhere (although I can't understand if it matters).

The thought that this brings to mind is that the build process is losing some sort of startup configuration. That might well include the definition of `parquet_scan` and such. The mystery is how csv data handling could have survived this rough handling.
```
julia> DuckDB.toDataFrame(DuckDB.execute(con, """PRAGMA version"""))
1×2 DataFrame
 Row │ library_version  source_id 
     │ String           String    
─────┼────────────────────────────
   1 │ v0.0.1-dev0

julia> 
tdunning@nodea:~$ ./duckdb 
v0.3.1 88aa81c6b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D PRAGMA version;
┌─────────────────┬───────────┐
│ library_version │ source_id │
├─────────────────┼───────────┤
│ v0.3.1          │ 88aa81c6b │
└─────────────────┴───────────┘
```

**Comment by kimmolinna** [comment]
It's not a path issue. Table function missing means that the parquet extension is not loaded. I will look at this.

**Comment by kimmolinna** [comment]
I made a pull request for Yggdrasil package but I wouldn't like to use version number 0.3.2 yet and 0.3.1 is already used without change for parquet file handling. The Package 0.3.1 supports parquet files automatically but when you are building it from source and via Binary Builder you have to give those flags manually. Maybe I just use version number 0.3.2 because otherwise we won't get wisely updateable package.

**Comment by tdunning** [comment]
is it possible to use something like 0.3.1+1 ? or 0.3.1.1?

**Comment by jeremiahpslewis** [comment]
This is a common binarybuilder topic, which usually doesn't lead to any major issues, personally I'd just go for the 1.3.2, other options just don't really work.

@kimmolinna did you check the version number issue @tdunning reported as well?

**Comment by kimmolinna** [comment]
I have done a new pull request with version number 0.3.2.  `PRAGMA version`  number is the default number because normally they use `git` to define the version.
```cmake
 # fallback for when building from tarball
  set(DUCKDB_MAJOR_VERSION 0)
  set(DUCKDB_MINOR_VERSION 0)
  set(DUCKDB_PATCH_VERSION 1)
  set(DUCKDB_DEV_ITERATION 0)
  set(DUCKDB_VERSION "v${DUCKDB_MAJOR_VERSION}.${DUCKDB_MINOR_VERSION}.${DUCKDB_PATCH_VERSION}-dev${DUCKDB_DEV_ITERATION}")
```

**Comment by jeremiahpslewis** [comment]
@kimmolinna Awesome, that explains why the random fix I tried earlier today worked; here's a PR which should resolve the issue: https://github.com/JuliaPackaging/Yggdrasil/pull/4244

**Comment by kimmolinna** [comment]
Guys, it's working with the latest version +2
```julia
DuckDB.toDataFrame(DuckDB.execute(con, "SELECT * FROM 'zstd.parquet'"))
3×3 DataFrame
 Row │ one        two     three
     │ Float64?   String  UInt8
─────┼──────────────────────────
   1 │      -1.0  foo         1
   2 │ missing    bar         0
   3 │       2.5  baz         1
```

**Comment by kimmolinna** [comment]
Thank you very @jeremiahpslewis and @tdunning. It's bit hard to remember everything because I have an interface for DuckDB also for Dyalog APL and last week I set up evertyhing so that I can crosscompile DuckDB from Windows/WSL2/Ubuntu directly to Windows. Without any CMake-files. Just source code and one Zig build-file. ;)

**Comment by tdunning** [comment]
Badaboom!

Impressive work guys. This is really slick.
