### ISSUE TITLE
Memory issues without close(database)

### ISSUE THREAD

**Issue by lars-dammann** [kimmolinna/DuckDB.jl#8]
I am connecting to a big DB from my jupyter notebook and run into memory issues. For example running this code kills my kernel.
```
using DuckDB

"""
Queries a big DuckDB database
"""
function query_db()
    # Establish connection to DuckDB database
    con = connect("path/to/big_db")
    # Perfom query
    df = toDataFrame(con, "select avg(example_column) from example_table;")
    # Disconnect from the database
    disconnect(con)
    return df
end

result1 = query_db()
result2 = query_db()
```
The problem seems to be that `connect(path::String)` calls `duckdb_open(path, database)` and also doens't return the pointer to the DB but `disconnect(connection)` doesn't call `duckdb_close(database)`. So there is no possibility to close the database again when `connect(path::String)` is used. Therefore, memory allocated for the database is never de-allocated and running the function twice kills the kernel. Closing the database in query_db() seems to solve the problem.

Would it make sense to let `connect(path::String)` also return the pointer to the database and not only to the connection to make it possible to close the database after usage and/or make `disconnect(connection)` close the database to resolve the asymmetry?

**Comment by kimmolinna** [comment]
I will fix this. It's wise to have a possibility to close a database and when `disconnect(connection)` should close the database too. Thanks for report.

**Comment by kimmolinna** [comment]
I tried to be too clever earlier. Now I did it so that you first open database and after that you create connection. And you will get too different handles.
```julia
db = DuckDB.open(":memory:")
con = DuckDB.connect(db)
DuckDB.disconnect(con)
DuckDB.close(db)
```
This gives you better control over databases and connections. And hopefully this fix memory problems too.
@lars-dammann  Could you kindly confirm that this fix solved your problem before I close the issue.

**Comment by asbisen** [comment]
Thanks the latest commit fixes this issue. Interestingly I just experienced the same issue while iterating over multiple parquet files in a loop on a long running Julia program.

**Comment by lars-dammann** [comment]
Thanks a lot for this swift commit. Works like a charm now!
